flow:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: "{{ env_var('account') }}"
      role: "{{ env_var('role') }}"
      user: "{{ env_var('user') }}"
      password: "{{ env_var('password') }}"
      region: "{{ env_var('region') }}"
      database: "{{ env_var('database_dev') }}"
      warehouse: "{{ env_var('warehouse_dev') }}"
      schema: SILVER
      threads: 4
      client_session_keep_alive: False
      query_tag: gh_actions
    prod:
      type: snowflake
      account: "{{ env_var('account') }}"
      role: "{{ env_var('role') }}"
      user: "{{ env_var('user') }}"
      password: "{{ env_var('password') }}"
      region: "{{ env_var('region') }}"
      database: "{{ env_var('database_prod') }}"
      warehouse: "{{ env_var('warehouse_prod') }}"
      schema: silver
      threads: 4
      client_session_keep_alive: False
      query_tag: gh_actions
