flow:
  outputs:
    dev:
      account: vna27887.us-east-1
      client_session_keep_alive: false
      database: FLOW_DEV
      authenticator: externalbrowser
      region: us-east-1
      role: INTERNAL_DEV
      schema: SILVER
      threads: 4
      type: snowflake
      user: juan@flipsidecrypto.com
      warehouse: DATA_SCIENCE
    prod:
      account: vna27887.us-east-1
      client_session_keep_alive: false
      database: FLOW
      authenticator: externalbrowser
      region: us-east-1
      role: DBT_CLOUD_NEAR
      schema: SILVER
      threads: 4
      type: snowflake
      user: juan@flipsidecrypto.com
      warehouse: DATA_SCIENCE
  target: dev
