flow:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: vna27887.us-east-1
      role: INTERNAL_DEV
      user: sairaj@flipsidecrypto.com
      authenticator: externalbrowser
      region: us-east-1
      database: FLOW_DEV
      warehouse: DBT
      schema: SILVER
      threads: 8
      client_session_keep_alive: False
    prod:
      type: snowflake
      account: vna27887.us-east-1
      role: DBT_CLOUD_FLOW
      user: sairaj@flipsidecrypto.com
      authenticator: externalbrowser
      region: us-east-1
      database: flow
      warehouse: DBT
      schema: SILVER
      threads: 8
      client_session_keep_alive: False
  config:
    send_anonymous_usage_stats: False
