name: dbt_test_workflow
run-name: dbt_test_workflow

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}

jobs:
  called_workflow_template:
    uses: FlipsideCrypto/analytics-workflow-templates/.github/workflows/dbt_run_template_vars.yml@main
    with:
      dbt_command: >
        dbt run -s core__fact_blocks
      environment: workflow_prod
      warehouse: ${{ vars.WAREHOUSE }}
    secrets: inherit 
