name: integration test
run-name: ${{ github.event.inputs.branch }}

on:
  workflow_dispatch:
  

concurrency: ${{ github.workflow }}

jobs:
  test:
    name: integration_test
    uses: ./.github/workflows/dbt.yml
    secrets: inherit
  
    with:
      warehouse: DBT_CLOUD
      environment: ${{ github.ref == 'refs/heads/main' && 'workflow_prod' || 'workflow_dev' }}
      command: dbt test --selector 'integration_tests'
