name: dbt_test_scheduled
run-name: dbt_test_scheduled

on:
  workflow_dispatch:
  schedule:
    # Run at 1600 UTC daily (see https://crontab.guru)
    - cron: '0 16 * * *'
env:
  DBT_PROFILES_DIR: "${{ secrets.DBT_PROFILES_DIR }}"
  DBT_VERSION: "${{ secrets.DBT_VERSION }}"
  ACCOUNT: "${{ secrets.ACCOUNT }}"
  ROLE: "${{ secrets.ROLE }}"
  USER: "${{ secrets.USER }}"
  PASSWORD: "${{ secrets.PASSWORD }}"
  REGION: "${{ secrets.REGION }}"
  DATABASE: "${{ secrets.DATABASE }}"
  WAREHOUSE: "${{ secrets.WAREHOUSE }}"
  SCHEMA: "${{ secrets.SCHEMA }}"

concurrency:
  group: ${{ github.workflow }}

jobs:
  called_workflow_template:
    uses: FlipsideCrypto/analytics-workflow-templates/.github/workflows/dbt_run_template.yml@main
    with:
      dbt_command: "[\"dbt test\"]"
      environment: workflow_prod
      warehouse: ${{ vars.WAREHOUSE }}
    secrets: inherit 
