name: dbt_run_scheduled_reward_points_realtime
run-name: dbt_run_scheduled_reward_points_realtime

on:
  workflow_dispatch:
  schedule:
    # Daily at 00:00 UTC
    - cron: "0 0 * * *"

env:
  USE_VARS: "${{ vars.USE_VARS }}"
  DBT_PROFILES_DIR: "${{ vars.DBT_PROFILES_DIR }}"
  DBT_VERSION: "${{ vars.DBT_VERSION }}"
  ACCOUNT: "${{ vars.ACCOUNT }}"
  ROLE: "${{ vars.ROLE }}"
  USER: "${{ vars.USER }}"
  PASSWORD: "${{ secrets.PASSWORD }}"
  REGION: "${{ vars.REGION }}"
  DATABASE: "${{ vars.DATABASE }}"
  WAREHOUSE: "${{ vars.WAREHOUSE }}"
  SCHEMA: "${{ vars.SCHEMA }}"
  FLOW_POINTS_URL: "${{ secrets.FLOW_POINTS_URL }}"
  PRIVATE_KEY: "${{ secrets.PRIVATE_KEY }}"
  PUBLIC_ADDRESS: "${{ secrets.PUBLIC_ADDRESS }}"

concurrency:
  group: ${{ github.workflow }}
    
jobs:
  dbt:
    runs-on: ubuntu-latest
    environment:
      name: workflow_prod
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"

      - name: install dependencies
        run: |
          pip install -r requirements.txt
          dbt deps

      - name: Request User Points Balances and Storefront Items
        run: >
          dbt run -s 1+streamline__reward_points_realtime streamline__minting_assets_realtime --vars '{"STREAMLINE_INVOKE_STREAMS": True}'

      - name: Authenticate with Flow Points API
        run: |
          python python/points/authenticate.py

      - name: Request Points Transfers
        run: >
          dbt run -s streamline__points_transfers_realtime --vars '{"STREAMLINE_INVOKE_STREAMS": True}'

      - name: Store logs
        uses: actions/upload-artifact@v4
        with:
          name: dbt-logs
          path: |
            logs
            target
