version: 2

sources:
  - name: prod
    database: chainwalkers
    schema: prod
    tables:
      - name: flow_blocks
      - name: flow_txs

  - name: crosschain
    database: flipside_prod_db
    schema: crosschain
    tables:
      - name: address_labels

  - name: silver
    database: flipside_prod_db
    schema: silver
    tables:
      - name: market_asset_metadata
      - name: prices_v2

  - name: bronze_streamline
    database: streamline
    schema: flow
    tables:
      - name: moments_minted_metadata_api    

  - name: crosschain_v2
    database: crosschain
    schema: core
    tables:
      - name: fact_hourly_prices
