version: 2

sources:
  - name: prod
    database: chainwalkers
    schema: prod
    tables:
      - name: flow_blocks
      - name: flow_txs

  - name: bronze_streamline
    database: streamline
    schema: |
      {{ "FLOW_DEV" if var("STREAMLINE_USE_DEV_FOR_EXTERNAL_TABLES", False) else "FLOW" }}
    tables:
      - name: moments_minted_metadata_api
      - name: blocks
      - name: collections
      - name: transactions
      - name: transaction_results
      - name: BLOCKS_CANDIDATE_07
      - name: BLOCKS_CANDIDATE_08
      - name: BLOCKS_CANDIDATE_09
      - name: BLOCKS_MAINNET_01
      - name: BLOCKS_MAINNET_02
      - name: BLOCKS_MAINNET_03
      - name: BLOCKS_MAINNET_04
      - name: BLOCKS_MAINNET_05
      - name: BLOCKS_MAINNET_06
      - name: BLOCKS_MAINNET_07
      - name: BLOCKS_MAINNET_08
      - name: BLOCKS_MAINNET_09
      - name: BLOCKS_MAINNET_10
      - name: BLOCKS_MAINNET_11
      - name: BLOCKS_MAINNET_12
      - name: BLOCKS_MAINNET_13
      - name: BLOCKS_MAINNET_14
      - name: BLOCKS_MAINNET_15
      - name: BLOCKS_MAINNET_16
      - name: BLOCKS_MAINNET_17
      - name: BLOCKS_MAINNET_18
      - name: BLOCKS_MAINNET_19
      - name: BLOCKS_MAINNET_20
      - name: BLOCKS_MAINNET_21
      - name: BLOCKS_MAINNET_22
      - name: COLLECTIONS_CANDIDATE_07
      - name: COLLECTIONS_CANDIDATE_08
      - name: COLLECTIONS_CANDIDATE_09
      - name: COLLECTIONS_MAINNET_01
      - name: COLLECTIONS_MAINNET_02
      - name: COLLECTIONS_MAINNET_03
      - name: COLLECTIONS_MAINNET_04
      - name: COLLECTIONS_MAINNET_05
      - name: COLLECTIONS_MAINNET_06
      - name: COLLECTIONS_MAINNET_07
      - name: COLLECTIONS_MAINNET_08
      - name: COLLECTIONS_MAINNET_09
      - name: COLLECTIONS_MAINNET_10
      - name: COLLECTIONS_MAINNET_11
      - name: COLLECTIONS_MAINNET_12
      - name: COLLECTIONS_MAINNET_13
      - name: COLLECTIONS_MAINNET_14
      - name: COLLECTIONS_MAINNET_15
      - name: COLLECTIONS_MAINNET_16
      - name: COLLECTIONS_MAINNET_17
      - name: COLLECTIONS_MAINNET_18
      - name: COLLECTIONS_MAINNET_19
      - name: COLLECTIONS_MAINNET_20
      - name: COLLECTIONS_MAINNET_21
      - name: COLLECTIONS_MAINNET_22
      - name: TRANSACTIONS_CANDIDATE_07
      - name: TRANSACTIONS_CANDIDATE_08
      - name: TRANSACTIONS_CANDIDATE_09
      - name: TRANSACTIONS_MAINNET_01
      - name: TRANSACTIONS_MAINNET_02
      - name: TRANSACTIONS_MAINNET_03
      - name: TRANSACTIONS_MAINNET_04
      - name: TRANSACTIONS_MAINNET_05
      - name: TRANSACTIONS_MAINNET_06
      - name: TRANSACTIONS_MAINNET_07
      - name: TRANSACTIONS_MAINNET_08
      - name: TRANSACTIONS_MAINNET_09
      - name: TRANSACTIONS_MAINNET_10
      - name: TRANSACTIONS_MAINNET_11
      - name: TRANSACTIONS_MAINNET_12
      - name: TRANSACTIONS_MAINNET_13
      - name: TRANSACTIONS_MAINNET_14
      - name: TRANSACTIONS_MAINNET_15
      - name: TRANSACTIONS_MAINNET_16
      - name: TRANSACTIONS_MAINNET_17
      - name: TRANSACTIONS_MAINNET_18
      - name: TRANSACTIONS_MAINNET_19
      - name: TRANSACTIONS_MAINNET_20
      - name: TRANSACTIONS_MAINNET_21
      - name: TRANSACTIONS_MAINNET_22
      - name: TRANSACTION_RESULTS_CANDIDATE_07
      - name: TRANSACTION_RESULTS_CANDIDATE_08
      - name: TRANSACTION_RESULTS_CANDIDATE_09
      - name: TRANSACTION_RESULTS_MAINNET_01
      - name: TRANSACTION_RESULTS_MAINNET_02
      - name: TRANSACTION_RESULTS_MAINNET_03
      - name: TRANSACTION_RESULTS_MAINNET_04
      - name: TRANSACTION_RESULTS_MAINNET_05
      - name: TRANSACTION_RESULTS_MAINNET_06
      - name: TRANSACTION_RESULTS_MAINNET_07
      - name: TRANSACTION_RESULTS_MAINNET_08
      - name: TRANSACTION_RESULTS_MAINNET_09
      - name: TRANSACTION_RESULTS_MAINNET_10
      - name: TRANSACTION_RESULTS_MAINNET_11
      - name: TRANSACTION_RESULTS_MAINNET_12
      - name: TRANSACTION_RESULTS_MAINNET_13
      - name: TRANSACTION_RESULTS_MAINNET_14
      - name: TRANSACTION_RESULTS_MAINNET_15
      - name: TRANSACTION_RESULTS_MAINNET_16
      - name: TRANSACTION_RESULTS_MAINNET_17
      - name: TRANSACTION_RESULTS_MAINNET_18
      - name: TRANSACTION_RESULTS_MAINNET_19
      - name: TRANSACTION_RESULTS_MAINNET_20
      - name: TRANSACTION_RESULTS_MAINNET_21
      - name: TRANSACTION_RESULTS_MAINNET_22
      - name: testnet_blocks
      - name: testnet_collections
      - name: testnet_transactions
      - name: testnet_transaction_results
      - name: evm_blocks
      - name: evm_receipts
      - name: evm_traces

  - name: crosschain_silver
    database: crosschain
    schema: silver
    tables:
      - name: labels_combined

  - name: silver_crosschain
    database: "{{ 'crosschain' if target.database == 'FLOW' else 'crosschain_dev' }}"
    schema: silver
    tables:
      - name: complete_token_asset_metadata
      - name: complete_token_prices
      - name: complete_provider_asset_metadata
      - name: complete_provider_prices
      - name: complete_native_asset_metadata
      - name: complete_native_prices
      - name: number_sequence
      - name: labels_combined

  - name: bronze_api
    database: |
      {{ "FLOW" if target.database == 'FLOW' else "FLOW_DEV" }}
    schema: |
      bronze_api
    tables:
      - name: allday_metadata

  - name: flow_bronze
    database: |
      {{ "FLOW" if target.database == 'FLOW' else "FLOW_DEV" }}
    schema: bronze
    tables:
      - name: ufc_strike_metadata
      - name: espn_nfl_teams
      - name: espn_nfl_athletes
