version: 2

sources:
  - name: prod
    database: chainwalkers
    schema: prod
    tables:
      - name: flow_blocks
      - name: flow_txs

  - name: crosschain_core
    database: crosschain
    schema: core
    tables:
      - name: address_labels

  - name: silver
    database: flipside_prod_db
    schema: silver
    tables:
      - name: market_asset_metadata
      - name: prices_v2

  - name: bronze_streamline
    database: streamline
    schema: flow
    tables:
      - name: moments_minted_metadata_api

  - name: crosschain_silver
    database: crosschain
    schema: silver
    tables:
      - name: hourly_prices_coin_gecko
      - name: hourly_prices_coin_market_cap
      - name: number_sequence
